### ISSUE TITLE
Invalidating cached fields

### ISSUE THREAD

**Issue by Amnesthesia** [stackshareio/graphql-cache#37]
Is there any way to invalidate cached fields? It would be great if, during a mutation, you could also invalidate fields that have been cached

**Comment by chadwilken** [comment]
It uses standard cache invalidation techniques utilized by Rails as you can see [here](https://github.com/stackshareio/graphql-cache/blob/master/lib/graphql/cache/key.rb#L92). If you wanted, you could also call `GraphQL::Cache.delete`, which would just forward to [this](https://api.rubyonrails.org/classes/ActiveSupport/Cache/Store.html#method-i-delete).
