### ISSUE TITLE
Allow "cache: true" for interface types

### ISSUE THREAD

**Issue by jeromedalbert** [stackshareio/graphql-cache#46]
When I try to add `cached: true` on an interface I get `unknown keyword: cache`.

The underlying class used in an interface field is different maybe, which could be why it doesn't work.

**Comment by thebadmonkeydev** [comment]
@jeromedalbert I took a look and the reason it is not recognizing the custom metadata is because the graphql-cache field_class is only set on the base object type, not the base interface type.  If you add:

```ruby
field_class GraphQL::Cache::Field
```
to your base interface module, those fields will recognize the `cache` param.

**Comment by thebadmonkeydev** [comment]
I just pushed #47 that adds a clarifying note about this usage of `field_class` to the README.
